# Azure App Service GitHub Actions Workflow
name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: my-chatbot-app-73d666
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt
    
    - name: Verify deployment files
      run: |
        echo "Checking deployment files..."
        ls -la
        echo "Checking startup.py exists:"
        ls -la startup.py
        echo "Checking run.py exists:"
        ls -la run.py
        echo "Checking web.config exists:"
        ls -la web.config
        echo "Checking app directory:"
        ls -la app/
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Restart Azure App Service
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group chatbot-rg
